name: Python Vulture Action
author: Anay Nayak
description: "Run vulture to analyse dead code in python projects"
inputs:
  vulture-args:
    description: "cli arguments passed to vulture"
    required: true
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.vulture-args }}
branding:
  icon: "feather"
  color: "orange"
