name: "Vulture"
description: "Run vulture to analyse dead code in python projects"
inputs:
  vulture-args:
    description: "vulture args"
    required: true
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.vulture-args }}
branding:
  icon: 'feather'
  color: 'gray-dark'
